all:
	#python3 -m pip install shiv wheel
	#python3 setup.py sdist bdist_wheel
	#python3 -m shiv -c tottag -o tottag . --no-user
	python3 -m pip install .
	rm -rf build dist tottag* *.egg-info

clean:
	rm -rf build dist tottag* *.egg-info
