name: Compilation CI
on: [push]

jobs:
  compile-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '11.3.Rel1'
      - name: compile-revM
        run: pushd software/firmware && make clean && make -j all BOARD_REV=M
